version: '3.8'

services:
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mz-frontend
    restart: unless-stopped
    expose:
      - "80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mz-backend
    restart: unless-stopped
    expose:
      - "3333"
    environment:
      - DB_HOST=postgres-db
      - DB_USER=mzadmin
      - DB_PASS=mzsenha2026
      - DB_NAME=mz_importados
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:15-alpine
    container_name: mz-database
    restart: unless-stopped
    expose:
      - "5432"
    environment:
      POSTGRES_USER: mzadmin
      POSTGRES_PASSWORD: mzsenha2026
      POSTGRES_DB: mz_importados
    volumes:
      - mz-pg-data:/var/lib/postgresql/data

volumes:
  mz-pg-data: 
